
image:
  repository: wooferclaw/s3-mounter-hack
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  name: s3-otomounter

bucketName: spt-cache-bucket
iamRoleARN: arn:aws:iam::279465261568:role/userServiceRoleEksS3Otomounter
hostPath: /mnt/s3data
# This is a variable to customize the command and manage option
#commandOption: 
#  - ./run-hack.sh
  

